apiVersion: v1
kind: Secret
metadata:
  name: mysql-secrets
  namespace: mysql
type: Opaque
data:
  MYSQL_ROOT_PASSWORD: MTIzNA==
  MYSQL_USER: YXBwX3VzZXI=
  MYSQL_PASSWORD: MTIzNA==

#MYSQL_ROOT_PASSWORD: 1234
#MYSQL_USER: app_user
#MYSQL_PASSWORD: 1234